name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}

      - uses: actions/cache@v4
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json') }}

      - uses: actions/cache@v4
        with:
          path: elm-stuff
          key: elm-stuff

      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit

      - run: ls -ohRS elm-stuff || true

      - run: node gen.mjs

      - run: ls -ohRS src || true

      - run: touch -d "2026-01-15 14:30:00" src/*.elm

      - run: ls -ohRS src || true

      - run: time npx elm make --output=/dev/null src/Main.elm
